name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: macOS-latest
    strategy:
      matrix:
        env:
          - sdk: iphonesimulator11.4
            destination: platform=iOS Simulator,name=iPhone 8,OS=11.4
            xcode: /Applications/Xcode_9.4.1.app

          - sdk: iphonesimulator12.4
            destination: platform=iOS Simulator,name=iPhone 8,OS=12.4
            xcode: /Applications/Xcode_10.3.app

          - sdk: iphonesimulator13.0
            destination: platform=iOS Simulator,name=iPhone 8,OS=13.0
            xcode: /Applications/Xcode_11.app

    steps:
    - uses: actions/checkout@v1

    - name: Select Xcode
      run: sudo xcode-select -s ${{ matrix.env.xcode }}

    - name: Build and Test
      run: |
        set -o pipefail && xcodebuild clean build test \
          -project "$PROJECT" \
          -scheme "$SCHEME" \
          -sdk "$SDK" \
          -destination "$DESTINATION" \
          -configuration Debug \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
      env:
        PROJECT: UITextView+Placeholder.xcodeproj
        SCHEME: UITextView+Placeholder
        SDK: ${{ matrix.env.sdk }}
        DESTINATION: ${{ matrix.env.destination }}
